### ISSUE TITLE
Failed to resolve import

### ISSUE THREAD

**Issue by LionisIAm** [MaksymMakiaveli/SoftPear_Test_Task#14]
<img width="1346" alt="Screenshot 2024-03-25 at 18 17 54" src="https://github.com/MaksymMakiaveli/SoftPear_Test_Task/assets/7932024/c137e56e-d7e6-4598-8f51-3cbafbf675d6">

**Comment by LionisIAm** [comment]
I think we need to change here https://github.com/MaksymMakiaveli/SoftPear_Test_Task/blob/master/src/shared/UI/common/index.ts
this: 
`export * from './each';`
to
`export * from './Each';`

**Comment by MaksymMakiaveli** [comment]
Thanks for your attention, I spent a few hours to catch that error. Really, thank you
